### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jonatanblockchain** [punica-box/bitcoin-catcher-box#31]
![2019-07-27 13_05_39-Window](https://user-images.githubusercontent.com/29895459/61993714-fcc2e400-b06f-11e9-9c2c-5ecfc6916bf8.png)

**Comment by NashMiao** [comment]
Thnaks, I correct it now.

![image](https://user-images.githubusercontent.com/18191964/62009283-0ba0b800-b190-11e9-9915-d8710114638c.png)
